name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Test
        run: npm test

      - name: Release and publish to npm
        if: success()
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"
          npm version patch -m "chore(release): %s [skip ci]"
          VERSION=$(node -p "require('./package.json').version")
          echo "Creating release for version $VERSION"
          body=$(echo "{}" | jq --arg version "$VERSION" '.body = "Release version \($version)"')
          response=$(curl --silent --request POST --url "https://api.github.com/repos/$GITHUB_REPOSITORY/releases" \
            --header "authorization: Bearer $GITHUB_TOKEN" \
            --header "content-type: application/json" \
            --data "$body")
          release_id=$(echo "$response" | jq -r '.id')
          echo "Release created with ID $release_id"
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm publish --access public

      - name: Create tag
        if: success()
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"
          VERSION=$(node -p "require('./package.json').version")
          echo "Creating tag for version $VERSION"
          git tag -a v${VERSION} -m "Release version ${VERSION}"
          git push origin v${VERSION}
          TAG=$(git tag -l --points-at HEAD)
          echo "Tag $TAG created"

