name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Test
        run: npm test

      - name: Create GitHub Release
        if: success()
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: "Release version v${{ steps.get_version.outputs.version }}"
          draft: false
          prerelease: false

      - name: Publish to npm
        if: success()
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm publish --access public
          echo "Release published to npm"

      - name: Publish to GitHub Package Registry
        if: success()
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GPR_TOKEN" > .npmrc
          npm publish
          echo "Release published to GitHub Package Registry"

      - name: Get package version
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"
